djangoAppProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account.views import user_registration, user_login, user_logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('registration/', user_registration, name='registration'),
    path('', include('main_page.urls')),
    path('manager/', include('manager.urls'), name='manager')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from .views import reservation_list, reservation_update

app_name = 'manager'

urlpatterns = [
    path('reservations/', reservation_list, name='reservation_list'),
    path('reservations/update/<int:pk>/', reservation_update, name='reservation_close'),

]

manager/models.py
from django.db import models


# Create your models here.
class UserReservations(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    message = models.TextField(max_length=500)
    order_date = models.TextField(max_length=11)
    order_time = models.TextField(max_length=6)
    num_of_people = models.SmallIntegerField()

    is_processed = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('date', )

    def __str__(self):
        return f"{self.name}, mob #: {self.phone}. Persons: {self.num_of_people}. " \
               f"Date: {self.order_date}, time: {self.order_time}, message: {self.message[:20]}. " \
               f"Status: {self.is_processed}"

manager/views.py
from django.shortcuts import render, redirect
from .models import UserReservations
from django.contrib.auth.decorators import login_required, user_passes_test
# Create your views here.


@login_required(login_url='/login/')
@user_passes_test(lambda user: user.groups.filter(name='manager').exists())
def reservation_list(request):
    lst = UserReservations.objects.filter(is_processed=False)
    return render(request, 'reservation_list.html', context={'lst': lst})


@login_required(login_url='/login/')
@user_passes_test(lambda user: user.groups.filter(name='manager').exists())
def reservation_update(request, pk):
    UserReservations.objects.filter(pk=pk).update(is_processed=True)
    return redirect('manager:reservation_list')

manager/templates/reservation_list.html
{% extends 'index.html' %}

{% block main_content %}
    <section id="reserves">
        <div class="container">
            <div class="col-md-10 col-md-offset-1">
                {% for item in lst %}
                    <div class="row">
                        <div class="col-md-3">
                            <a href="{% url 'manager:reservation_close' pk=item.pk %}">
                                <button type="button" class="btn btn-primary">Close request</button>
                            </a>
                        </div>
                        <div class="col-md-3">Name: {{ item.name }}</div>
                        <div class="col-md-3">Phone num.: {{ item.phone }}</div>
                        <div class="col-md-3">Request date: {{ item.date|date:'d.m.Y' }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-3"><p>Reservation date: {{ item.order_date }} </p></div>
                        <div class="col-md-3"><p>Reservation time: {{ item.order_time }} </p></div>
                        <div class="col-md-3"><p>Comments: {{ item.message }} </p></div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}